Obstacle avoidance
DIT113-V22/group-10 pull request #26
Opened 2022-04-04 13:50 UTC by DanielJCoetzer

Fixed speed issue

2022-04-04 14:31 UTC, platisd commented
What happened to #25 ? Push a new commit to that branch and let's continue the pull request there. No reason to create a new one.

2022-04-04 14:33 UTC, platisd commented
Anyway, I see that you have deleted the old branch. There's no need to open a new pull request every time. Simply, push to the same branch that the pull request is originating from and then the pull request will be updated.

2022-04-04 14:34 UTC, platisd requested changes
I don't think you should merge this. Something has gone wrong in what you are trying to push.

2022-04-06 11:40 UTC, platisd requested changes
This branch is in an extremely confusing (and bad) state. Best is to start from scratch.

2022-04-06 15:38 UTC, platisd requested changes

2022-04-06 17:07 UTC, DanielJCoetzer commented on arduino/Obstacle_Avoidance/Obstacle_Avoidance.ino
> +  if(front.getDistance() >= 100 || front.getDistance()==0)
Won't the car stop? 
The car only drives if 'getDistance' is '0' or more than a 100, so if it is '5' shouldn't it stop?

2022-04-06 17:10 UTC, DanielJCoetzer commented on Android/app/src/androidTest/java/com/example/hermes/ExampleInstrumentedTest.java
>  }
Yeah I will make a new branch with only the sketch.

2022-04-06 17:12 UTC, DanielJCoetzer commented on arduino/Obstacle_Avoidance/Obstacle_Avoidance.ino
> +#include <Smartcar.h>
Are we supposed to only change the already provided `smartcar.ino` file?

2022-04-06 17:47 UTC, platisd commented on arduino/Obstacle_Avoidance/Obstacle_Avoidance.ino
> +  if(front.getDistance() >= 100 || front.getDistance()==0)
OK, I think I messed up a bit. Let's try again:

What happens if the first call to `getDistance` is `0` and the next one returns `100`? It stops when it should drive.

2022-04-06 17:50 UTC, platisd commented on Android/app/src/androidTest/java/com/example/hermes/ExampleInstrumentedTest.java
>  }
You should instead try to use `git`.
E.g. if your local `master` is in a good state you can do `git checkout master Android/app/src/androidTest/java/com/example/hermes/ExampleInstrumentedTest.java`

2022-04-06 17:59 UTC, DanielJCoetzer commented on arduino/Obstacle_Avoidance/Obstacle_Avoidance.ino
> +  if(front.getDistance() >= 100 || front.getDistance()==0)
To my understanding of this code, if `getDistance` is 100 it will drive.

2022-04-06 18:08 UTC, platisd commented on arduino/Obstacle_Avoidance/Obstacle_Avoidance.ino
> +  if(front.getDistance() >= 100 || front.getDistance()==0)
You have 2 calls to `getDistance` on that line. Which of the two are you referring to?

2022-04-06 18:11 UTC, DanielJCoetzer commented on arduino/Obstacle_Avoidance/Obstacle_Avoidance.ino
> +  if(front.getDistance() >= 100 || front.getDistance()==0)
OH I SEE what you mean. I forgot that calling `getDistance ` behaves like that. Thank you for your patience!

2022-04-11 08:59 UTC, closed without merging